name: Build Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Build Binary
      run: go build -o mybinary https://github.com/stacy-smirnova/devops-2024/blob/839309acb7dc11e857aab6ab7dd269fcdcd3861e/main.py

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: mybinary
        path: mybinary