name: Build Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Binary
      run: g++ build main.cpp -o mybinary
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: mybinary
        path: mybinary